[workspace]
members = [
    "ambient_download", "json2csv", "playground", "shared",
]
resolver = "2"

[workspace.package]
# name = "Ambient Weather Tools"
version = "0.4.0"
edition = "2021"
authors = ["Even Solberg <even.solberg@gmail.com>"]
readme = "README.md"
description = "Tools for downloading data from the Ambient Weather API and detecting the timezone of a location."
repository = "https://github.com/evensolberg/ambient_tools"
homepage = "https://github.com/evensolberg/ambient_tools"

[workspace.dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
chrono-tz = { version = "0.10.4", features = [ "case-insensitive", "serde" ] }
clap = { version = "4.5.51", features = ["cargo", "env", "wrap_help"] }
env_logger = "0.11.8"
iana-time-zone = "0.1.64"
log = "0.4.28"
reqwest = { version = "0.12.24", features = ["json", "blocking"] } # reqwest with JSON parsing support
serde = { version = "1.0.228", features = ["derive"] } # for JSON serialization
serde_json = "1.0.145"
toml = "0.9.8"
shared = { path = "../shared" }

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.15.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false

[profile.release]
strip = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
