use clap::{Arg, Command}; // Command line

#[allow(clippy::too_many_lines, clippy::module_name_repetitions)]
pub fn build_cli() -> Command {
    Command::new(clap::crate_name!())
        .about(clap::crate_description!())
        .version(clap::crate_version!())
        .author(clap::crate_authors!("\n"))
        .long_about("Download weather data from Ambient Weather API.")
        .arg( // Output detail level
            Arg::new("detail")
                .short('d')
                .long("detail-level")
                .help("Output detail level")
                .long_help("Output detail level. 0=Quiet, 1=Normal, 2=Detailed, 3=Debug, 4=Trace.")
                .num_args(1)
                .action(clap::ArgAction::Set)
                .env("AMBIENT_WEATHER_DETAIL_LEVEL")
                .default_value("1")
                .value_parser(clap::value_parser!(u8).range(..=4))
        )
        .arg( // API Key
            Arg::new("api-key")
            .short('k')
            .long("api-key")
            .help("The Ambient Weather API key.")
            .long_help("The Ambient Weather API key. If not provided, the value is read from the environment variable AMBIENT_WEATHER_API_KEY.")
            .num_args(0)
            .action(clap::ArgAction::Set)
            .env("AMBIENT_WEATHER_API_KEY")
        )
        .arg( // Application Key
            Arg::new("app-key")
            .short('l')
            .long("app-key")
            .help("The Ambient Weather Application key.")
            .long_help("The Ambient Weather Application key. If not provided, the value is read from the environment variable AMBIENT_WEATHER_APP_KEY.")
            .num_args(0)
            .action(clap::ArgAction::Set)
            .env("AMBIENT_WEATHER_APP_KEY")
        )
        .arg( // Output folder
            Arg::new("output-folder")
            .short('o')
            .long("output-folder")
            .help("The folder into which the output files are to be written.")
            .long_help("The folder into which the output files are to be written. Default is the current folder if not specified.")
            .action(clap::ArgAction::Set)
            .env("AMBIENT_WEATHER_OUTPUT_FOLDER")
            .default_value(".")
        )
        .arg( // Config-file
            Arg::new("config-file")
            .short('c')
            .long("config-file")
            .help("The configuration file to use.")
            .long_help("The configuration file in TOML format to use. If not provided, the values are read from the command line.")
            .action(clap::ArgAction::Set)
            // .env("AMBIENT_WEATHER_CONFIG_FILE")
            // .default_value("ambient_download.toml")
            // .conflicts_with_all(["detail", "api-key", "app-key", "output-folder"])
        )
        .subcommand(Command::new("device")
            .about("Download device information.")
            .arg( // Device info JSON filename
                Arg::new("device-info-filename")
                .short('f')
                .long("device-info-filename")
                .help("The name of the file into which the device information is to be written.")
                .long_help("The name of the file into which the device information is to be written. Default is 'device-info.json' if not specified.")
                .num_args(0..)
                .default_missing_value("device-info.json")
                .action(clap::ArgAction::Set)
            )
        )
        .subcommand(Command::new("weather")
            .about("Download weather information.")
            .arg( // MAC Address
                Arg::new("mac-address")
                .short('m')
                .long("mac-address")
                .help("The MAC address for the console for which we are downloading information.")
                .long_help("The MAC address for the console for which we are downloading information. If not provided, the value is read from the environment variable AMBIENT_WEATHER_MAC_ADDRESS.")
                .num_args(0..=1)
                .action(clap::ArgAction::Set)
                .env("AMBIENT_WEATHER_MAC_ADDRESS")
                .required(false)
            )
            .arg( // End date
                Arg::new("end-dates")
                    .value_name("DATE")
                    .help("The END date for the downloads, If nothing is entered, yesterday's date is used.")
                    .num_args(..=1)
                    .action(clap::ArgAction::Set)
            )
            .arg( // Limit
                Arg::new("limit")
                    .short('n')
                    .long("limit")
                    .help("The number of records to download.")
                    .long_help("The number of records to download. The maximum is 288 (one whole day). Default is 288 if not specified.")
                    .num_args(1)
                    .action(clap::ArgAction::Set)
                    .default_value("288")
                    .value_parser(clap::value_parser!(u16).range(..=288))
            )
            .arg( // Weather JSON filename
                Arg::new("days")
                    .short('d')
                    .long("days")
                    .help("The number of days to download.")
                    .long_help("The number of days to download. Default is 1 if not specified. Max is 1095 (3 years).")
                    .num_args(1)
                    .action(clap::ArgAction::Set)
                    .default_value("1")
                    .value_parser(clap::value_parser!(u16).range(..=1095))
            )
            .arg( // Time zone offset
                Arg::new("tz-offset")
                    .short('o')
                    .long("tz-offset")
                    .help("The time zone offset for the data.")
                    .long_help("The time zone offset for the data. If not provided, the value is read from the environment variable AMBIENT_WEATHER_TZ_OFFSET.")
                    .num_args(1)
                    .action(clap::ArgAction::Set)
                    .env("AMBIENT_WEATHER_TZ_OFFSET")
                    .conflicts_with("time-zone")
            )
            .arg(
                Arg::new("sleep-time")
                    .short('s')
                    .long("sleep-time")
                    .help("The time to sleep between downloads.")
                    .long_help("The time to sleep between downloads. Default is 10 seconds if not specified. Max is 3600 seconds (1 hour). The more records you download, the longer you should sleep between downloads.")
                    .num_args(1)
                    .action(clap::ArgAction::Set)
                    .default_value("10")
                    .value_parser(clap::value_parser!(u64).range(..=3600))
            )
        )
        .subcommand(Command::new("timezone")
            .about("Print the local time zone information.")
        )
        .subcommand(Command::new("newconfig")
            .about("Create a new, empty configuration file.")
            .arg( // Config-file
                Arg::new("config-file")
                    .value_name("FILENAME")
                    .help("The name of the configuration file to create.")
                    .long_help("The configuration file in TOML format to create. Default is 'ambient_download.toml' if not specified.")
                    .num_args(..=1)
            )
        )
}
