use clap::{parser, Arg, Command}; // Command line

pub fn build_cli() -> Command {
    Command::new(clap::crate_name!())
        .about(clap::crate_description!())
        .version(clap::crate_version!())
        .author(clap::crate_authors!("\n"))
        .long_about("Download weather data from Ambient Weather API.")
        .arg( // Print summary information
            Arg::new("print-summary")
                .short('p')
                .long("print-summary")
                .help("Print summary detail for each session processed.")
                .num_args(0)
                .action(clap::ArgAction::SetTrue)
        )
        .arg( // Show debug information
            Arg::new("debug")
                .short('d')
                .long("debug")
                .help("Show debug information.")
                .num_args(0)
                .action(clap::ArgAction::Count)
                .hide(true)
        )
        .arg( // Show detail information
            Arg::new("show-detail")
                .short('i')
                .long("show-detail")
                .help("Show detailed information about each item processed.")
                .num_args(0)
                .action(clap::ArgAction::SetTrue)
        )
        .arg( // Don't show information other than warnings and errors
            Arg::new("quiet")
                .short('q')
                .long("quiet")
                .help("Don't print anything to the console.")
                .num_args(0)
                .action(clap::ArgAction::SetTrue)
        )
        .arg( // API Key
            Arg::new("api-key")
            .short('k')
            .long("api-key")
            .help("The Ambient Weather API key.")
            .long_help("The Ambient Weather API key. If not provided, the value is read from the environment variable AMBIENT_WEATHER_API_KEY.")
            .num_args(0)
            .action(clap::ArgAction::Set)
            .env("AMBIENT_WEATHER_API_KEY")
            .required(true)
        )
        .arg( // Application Key
            Arg::new("app-key")
            .short('l')
            .long("app-key")
            .help("The Ambient Weather Application key.")
            .long_help("The Ambient Weather Application key. If not provided, the value is read from the environment variable AMBIENT_WEATHER_APP_KEY.")
            .num_args(0)
            .action(clap::ArgAction::Set)
            .env("AMBIENT_WEATHER_APP_KEY")
            .required(true)
        )
        .arg( // Output folder
            Arg::new("output-folder")
            .short('f')
            .long("output-folder")
            .help("The folder into which the output files are to be written.")
            .long_help("The folder into which the output files are to be written. Default is the current folder if not specified.")
            .action(clap::ArgAction::Set)
            .default_value(".")
        )
        .subcommand(Command::new("device")
            .about("Download device information."))
            .arg( // Device info JSON filename
                Arg::new("device-info-filename")
                .short('f')
                .long("device-info-filename")
                .help("The name of the file into which the device information is to be written.")
                .long_help("The name of the file into which the device information is to be written. Default is 'device-info.json' if not specified.")
                .num_args(0..)
                .default_missing_value("device-info.json")
                .action(clap::ArgAction::Set)
            )
        .subcommand(Command::new("weather")
            .about("Download weather information.")
            .arg( // MAC Address
                Arg::new("mac-address")
                .short('m')
                .long("mac-address")
                .help("The MAC address for the console for which we are downloading information.")
                .long_help("The MAC address for the console for which we are downloading information. If not provided, the value is read from the environment variable AMBIENT_WEATHER_MAC_ADDRESS.")
                .num_args(0)
                .action(clap::ArgAction::Set)
                .env("AMBIENT_WEATHER_MAC_ADDRESS")
                .required(true)
            )
            .arg( // End date
                Arg::new("end-dates")
                    .value_name("DATES")
                    .help("One or more dates(s), If nothing is entered, yesterday's date is used.")
                    .num_args(0..)
            )
            .arg( // Limit
                Arg::new("limit")
                    .short('n')
                    .long("limit")
                    .help("The number of records to download.")
                    .long_help("The number of records to download. The maximum is 288.")
                    .num_args(1)
                    .action(clap::ArgAction::Set)
                    .default_value("288")
                    .value_parser(clap::value_parser!(u16).range(..=288))
            )
            .arg( // Time zone
                Arg::new("time-zone")
                    .short('z')
                    .long("time-zone")
                    .help("The time zone for the data.")
                    .long_help("The time zone for the data. If not provided, the value is read from the environment variable AMBIENT_WEATHER_TIME_ZONE.")
                    .num_args(0)
                    .action(clap::ArgAction::Set)
                    .env("AMBIENT_WEATHER_TIME_ZONE")
            )
            .arg( // Time zone offset
                Arg::new("tz-offset")
                    .short('o')
                    .long("tz-offset")
                    .help("The time zone offset for the data.")
                    .long_help("The time zone offset for the data. If not provided, the value is read from the environment variable AMBIENT_WEATHER_TZ_OFFSET.")
                    .num_args(1)
                    .action(clap::ArgAction::Set)
                    .env("AMBIENT_WEATHER_TZ_OFFSET")
                    .conflicts_with("time-zone")
            ))
}
