[package]
name = "tz_detect"
version = "0.1.0"
edition = "2021"
authors = ["Even Solberg <even.solberg@gmail.com>"]
description = "Detect the timezone of a user based on OS settings."
license = "MIT"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
iana-time-zone = "0.1.60"
quote = { version = "1.0.36" }
serde = { version = "1.0.199", features = ["derive"] }
