[package]
name = "tz_detect"
version = "0.3.1"
edition = "2021"
authors = ["Even Solberg <even.solberg@gmail.com>"]
description = "Output the local and UTC time, the local offset, the local timezone offset, and the local timezone name."
license = "MIT"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.4", features = ["cargo", "derive", "env", "wrap_help"] }
iana-time-zone = "0.1.60"
libc = { version = "0.2.153" }
memchr = { version = "2.7.2" }
rustix = { version = "0.38.34", features = ["fs", "termios"] }
serde = { version = "1.0.199", features = ["derive"] }
syn = { version = "2.0.60", features = ["full", "visit"] }
toml = { version = "0.8.12", features = ["parse"] }
shared = { path = "../shared" }

[package.metadata.hackerman.stash.dependencies]
memchr = false
libc = false
clap = { version = "4.5.4", features = ["derive"] }
rustix = false
syn = false
