[package]
name = "shared"
version = "0.1.5"
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
iana-time-zone.workspace = true
log.workspace = true
serde.workspace = true
thiserror = "2"
toml.workspace = true

[dev-dependencies]
serde_json.workspace = true
